const menuButton=document.querySelector('.menu-toggle');
const menu=document.querySelector('#primary-nav');
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close menu':'Open menu');menu.classList.toggle('open',open)});
menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');menuButton?.setAttribute('aria-expanded','false')}));
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
const progress=document.querySelector('.page-progress span');const updateProgress=()=>{const max=document.documentElement.scrollHeight-innerHeight;const pct=max>0?scrollY/max*100:0;if(progress)progress.style.width=`${Math.min(100,Math.max(0,pct))}%`};addEventListener('scroll',updateProgress,{passive:true});updateProgress();
if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px 40px 0px'});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el))}else document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));
const sections=[...document.querySelectorAll('main section[id]')];const navLinks=[...document.querySelectorAll('.nav a[href^="#"]')];if('IntersectionObserver'in window){const navObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}}),{rootMargin:'-35% 0px -55% 0px'});sections.forEach(s=>navObs.observe(s))}
const openers=document.querySelectorAll('.project-open');openers.forEach(btn=>btn.addEventListener('click',()=>{const dialog=document.getElementById(btn.dataset.dialog);if(dialog?.showModal){dialog.showModal();document.body.classList.add('dialog-open')}}));
document.querySelectorAll('.project-dialog').forEach(dialog=>{dialog.querySelector('.dialog-close')?.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});dialog.addEventListener('close',()=>document.body.classList.remove('dialog-open'))});
